//
// Created by nicol on 15/11/2023.
//

#ifndef COLECCI_N_DE_EJERCICIOS_STL_TRIANGULO_H
#define COLECCI_N_DE_EJERCICIOS_STL_TRIANGULO_H


class triangulo {

};


#endif //COLECCI_N_DE_EJERCICIOS_STL_TRIANGULO_H
